"""Stable enum vocabulary shared by Kernel Core and every Knowledge HAT."""

from enum import Enum


class StableStringEnum(str, Enum):
    """String enum whose values are the canonical wire representation."""

    def __str__(self) -> str:
        return self.value


class KnowledgeRoute(StableStringEnum):
    PASS_THROUGH = "PASS_THROUGH"
    HAT_ASSIST = "HAT_ASSIST"
    HAT_ENFORCE = "HAT_ENFORCE"
    AMBIGUOUS = "AMBIGUOUS"


class ActionPolicy(StableStringEnum):
    ALLOW = "ALLOW"
    DENY_ACTION = "DENY_ACTION"
    REQUIRE_CONFIRMATION = "REQUIRE_CONFIRMATION"


class EvidenceStatus(StableStringEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT = "INSUFFICIENT"
    CONFLICTING = "CONFLICTING"
    UNAVAILABLE = "UNAVAILABLE"
    STALE = "STALE"
    INVALID = "INVALID"


class AnswerStatus(StableStringEnum):
    DRAFT = "DRAFT"
    PASS_THROUGH_RESULT = "PASS_THROUGH_RESULT"
    VERIFIED = "VERIFIED"
    VERIFIED_WITH_CONFLICTS = "VERIFIED_WITH_CONFLICTS"
    BLOCKED_NO_VERIFIED_EVIDENCE = "BLOCKED_NO_VERIFIED_EVIDENCE"
    BLOCKED_CONFLICTING_EVIDENCE = "BLOCKED_CONFLICTING_EVIDENCE"
    BLOCKED_VERIFICATION_FAILED = "BLOCKED_VERIFICATION_FAILED"
    BLOCKED_POLICY = "BLOCKED_POLICY"
    BLOCKED_STORAGE_UNAVAILABLE = "BLOCKED_STORAGE_UNAVAILABLE"
    BLOCKED_AMBIGUOUS_ROUTE = "BLOCKED_AMBIGUOUS_ROUTE"
    MODEL_GENERATION_FAILED = "MODEL_GENERATION_FAILED"


class MemoryTrustClass(StableStringEnum):
    CANONICAL_SOURCE_EVIDENCE = "CANONICAL_SOURCE_EVIDENCE"
    SHARED_HAT_VERIFIED_MEMORY = "SHARED_HAT_VERIFIED_MEMORY"
    PERSONAL_VERIFIED_PATCH = "PERSONAL_VERIFIED_PATCH"
    USER_ASSERTED_MEMORY = "USER_ASSERTED_MEMORY"
    MODEL_EXPERIENCE_HINT = "MODEL_EXPERIENCE_HINT"
    SESSION_MEMORY = "SESSION_MEMORY"


class MemoryConflictType(StableStringEnum):
    NO_CONFLICT = "NO_CONFLICT"
    LOWER_TRUST_CONFLICT = "LOWER_TRUST_CONFLICT"
    SAME_TRUST_CONFLICT = "SAME_TRUST_CONFLICT"
    TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
    SCOPE_CONFLICT = "SCOPE_CONFLICT"
    SOURCE_CONFLICT = "SOURCE_CONFLICT"


class MemoryTargetScope(StableStringEnum):
    SESSION = "SESSION"
    USER_PERSONAL_HAT = "USER_PERSONAL_HAT"
    SHARED_KNOWLEDGE_HAT = "SHARED_KNOWLEDGE_HAT"


class ProposalOrigin(StableStringEnum):
    KNOWLEDGE_KERNEL = "KNOWLEDGE_KERNEL"
    KNOWLEDGE_HUB = "KNOWLEDGE_HUB"
    CRITIC_PROMPT_LOOP = "CRITIC_PROMPT_LOOP"
    MODEL_VERIFIER = "MODEL_VERIFIER"
    USER_ENTRY = "USER_ENTRY"
    USER_DOCUMENT = "USER_DOCUMENT"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    SYSTEM_MIGRATION = "SYSTEM_MIGRATION"


class PatchState(StableStringEnum):
    DETECTED = "DETECTED"
    PROPOSED = "PROPOSED"
    EVIDENCE_BOUND = "EVIDENCE_BOUND"
    VALIDATED = "VALIDATED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    COMMITTED = "COMMITTED"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"


class PersonalMemorySpaceState(StableStringEnum):
    EMPTY = "EMPTY"
    CONFIGURED = "CONFIGURED"
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    ARCHIVED = "ARCHIVED"
    DELETED_PENDING = "DELETED_PENDING"
    DELETED = "DELETED"


class SharedPromotionState(StableStringEnum):
    SHARED_PROMOTION_PROPOSED = "SHARED_PROMOTION_PROPOSED"
    EVIDENCE_REVALIDATED = "EVIDENCE_REVALIDATED"
    DOMAIN_REVIEW_REQUIRED = "DOMAIN_REVIEW_REQUIRED"
    APPROVED_FOR_SHARED = "APPROVED_FOR_SHARED"
    SHARED_PATCH_COMMITTED = "SHARED_PATCH_COMMITTED"
    REJECTED = "REJECTED"


class ScopeComparisonMode(StableStringEnum):
    EXACT = "EXACT"
    IN_SET = "IN_SET"
    HIERARCHICAL = "HIERARCHICAL"
    RANGE = "RANGE"
    SEMVER = "SEMVER"
    TIMESTAMP = "TIMESTAMP"
    CUSTOM_HAT_RULE = "CUSTOM_HAT_RULE"


class StorageClass(StableStringEnum):
    CRDB_TRANSACTIONAL = "CRDB_TRANSACTIONAL"
    S3_GLOBAL_LOCKED_SNAPSHOT = "S3_GLOBAL_LOCKED_SNAPSHOT"
    S3_USER_PRIVATE_SNAPSHOT = "S3_USER_PRIVATE_SNAPSHOT"
    EXTERNAL_DERIVED = "EXTERNAL_DERIVED"
    SESSION_EPHEMERAL = "SESSION_EPHEMERAL"


class HatAuthorityDeclaration(StableStringEnum):
    NONE = "NONE"


class ScopeValueType(StableStringEnum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"
    STRING_SET = "STRING_SET"
    TIMESTAMP = "TIMESTAMP"
    SEMVER = "SEMVER"
    JSON = "JSON"


class MissingDimensionBehavior(StableStringEnum):
    REJECT = "REJECT"
    AMBIGUOUS = "AMBIGUOUS"
    USE_DEFAULT = "USE_DEFAULT"
    OPTIONAL = "OPTIONAL"


class CorrectionCandidateState(StableStringEnum):
    DETECTED = "DETECTED"
    PROPOSED = "PROPOSED"


class MemoryContentKind(StableStringEnum):
    FACTUAL = "FACTUAL"
    PREFERENCE = "PREFERENCE"
    WORKFLOW = "WORKFLOW"
    MODEL_EXPERIENCE = "MODEL_EXPERIENCE"
    SESSION = "SESSION"


class MemoryVisibility(StableStringEnum):
    SHARED = "SHARED"
    PERSONAL = "PERSONAL"
    SESSION = "SESSION"


class MemoryRetrievalStatus(StableStringEnum):
    ELIGIBLE = "ELIGIBLE"
    INACTIVE = "INACTIVE"
    REVOKED = "REVOKED"
    NOT_YET_VALID = "NOT_YET_VALID"
    STALE = "STALE"
    EXPIRED = "EXPIRED"
    SPACE_NOT_ACTIVE = "SPACE_NOT_ACTIVE"


class ActorType(StableStringEnum):
    USER = "USER"
    HUMAN_REVIEWER = "HUMAN_REVIEWER"
    SYSTEM = "SYSTEM"
    COMMIT_SERVICE = "COMMIT_SERVICE"
    KNOWLEDGE_KERNEL = "KNOWLEDGE_KERNEL"
    KNOWLEDGE_HAT = "KNOWLEDGE_HAT"
    KNOWLEDGE_HUB = "KNOWLEDGE_HUB"
    CRITIC_PROMPT_LOOP = "CRITIC_PROMPT_LOOP"
    MODEL = "MODEL"
    MODEL_VERIFIER = "MODEL_VERIFIER"
    MIGRATION_SERVICE = "MIGRATION_SERVICE"


class ApprovalDecision(StableStringEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class ApprovalRequirement(StableStringEnum):
    OWNER = "OWNER"
    DOMAIN_REVIEWER = "DOMAIN_REVIEWER"
    SYSTEM_MIGRATION_REVIEW = "SYSTEM_MIGRATION_REVIEW"


class ClaimVerdictStatus(StableStringEnum):
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    INSUFFICIENT = "INSUFFICIENT"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"
    STALE = "STALE"


class PrivateDataClassification(StableStringEnum):
    NONE = "NONE"
    PERSONAL = "PERSONAL"
    SENSITIVE = "SENSITIVE"
    RESTRICTED = "RESTRICTED"


class DeidentificationStatus(StableStringEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED = "REQUIRED"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"


class ModelExperienceOutcome(StableStringEnum):
    CORRECTED = "CORRECTED"
    PARTIALLY_CORRECTED = "PARTIALLY_CORRECTED"
    NOT_CORRECTED = "NOT_CORRECTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
