"""Durable, authority-neutral Step 10 ingestion orchestration.

Importing this package performs no database, AWS, filesystem, subprocess,
network, model, HAT, parser, validator, publication, or cleanup action.
"""

from .errors import (
    FailureDecision,
    IngestionClaimError,
    IngestionConflictError,
    IngestionError,
    IngestionExecutionError,
    IngestionFailureClass,
    IngestionReceiptError,
    IngestionReconciliationError,
    IngestionTransitionError,
    IngestionValidationError,
    classify_ingestion_failure,
)
from .models import (
    INGESTION_CONTRACT_VERSION,
    INGESTION_GENESIS_DIGEST,
    INGESTION_SCHEMA_VERSION,
    MILESTONE_ORDER,
    ExternalEffectIntent,
    ExternalEffectKind,
    ExternalEffectReceipt,
    ExternalEffectRecord,
    ExternalEffectStatus,
    IngestionSaga,
    OrphanBackend,
    OrphanClassification,
    OrphanRecord,
    OrphanResolution,
    ParseReceipt,
    PublicationReceipt,
    SagaExecutionDisposition,
    SagaMilestone,
    SagaTransitionEvent,
    ValidationReceipt,
    build_initial_saga,
)
from .orchestrator import IngestionOrchestrator
from .protocols import (
    AcquisitionPort,
    IngestionSagaRepositoryProtocol,
    ParserPort,
    PlannedSnapshotStorageProtocol,
    PublicationPort,
    SagaControlProtocol,
    ValidatorPort,
)
from .publication import Step9PublicationPort
from .repository import (
    CockroachIngestionSagaRepository,
    effect_from_row,
    event_from_row,
    orphan_from_row,
    saga_from_row,
)
from .service import IngestionSagaService
from .state import (
    REQUIRED_RECEIPT_COUNTS,
    advance_saga,
    build_transition_event,
    next_milestone,
    require_milestone_transition,
    verify_saga_event_chain,
)


__all__ = [
    "AcquisitionPort",
    "CockroachIngestionSagaRepository",
    "ExternalEffectIntent",
    "ExternalEffectKind",
    "ExternalEffectReceipt",
    "ExternalEffectRecord",
    "ExternalEffectStatus",
    "FailureDecision",
    "INGESTION_CONTRACT_VERSION",
    "INGESTION_GENESIS_DIGEST",
    "INGESTION_SCHEMA_VERSION",
    "IngestionClaimError",
    "IngestionConflictError",
    "IngestionError",
    "IngestionExecutionError",
    "IngestionFailureClass",
    "IngestionOrchestrator",
    "IngestionReceiptError",
    "IngestionReconciliationError",
    "IngestionSaga",
    "IngestionSagaRepositoryProtocol",
    "IngestionSagaService",
    "IngestionTransitionError",
    "IngestionValidationError",
    "MILESTONE_ORDER",
    "OrphanBackend",
    "OrphanClassification",
    "OrphanRecord",
    "OrphanResolution",
    "ParseReceipt",
    "ParserPort",
    "PlannedSnapshotStorageProtocol",
    "PublicationPort",
    "PublicationReceipt",
    "REQUIRED_RECEIPT_COUNTS",
    "SagaControlProtocol",
    "SagaExecutionDisposition",
    "SagaMilestone",
    "SagaTransitionEvent",
    "Step9PublicationPort",
    "ValidationReceipt",
    "ValidatorPort",
    "advance_saga",
    "build_initial_saga",
    "build_transition_event",
    "classify_ingestion_failure",
    "effect_from_row",
    "event_from_row",
    "next_milestone",
    "orphan_from_row",
    "require_milestone_transition",
    "saga_from_row",
    "verify_saga_event_chain",
]
