"""Step 19 local embedding generation and vector retrieval foundation."""

from .backend import EmbeddingBackend, EmbeddingBackendIdentity, PassageEmbeddingBatch
from .cache import PassageEmbeddingCache
from .models import (
    APPROVED_EMBEDDING_DIMENSION,
    APPROVED_INPUT_POLICY,
    APPROVED_MAXIMUM_TOKENS,
    APPROVED_MODEL_ID,
    APPROVED_MODEL_LICENSE,
    APPROVED_MODEL_REVISION,
    APPROVED_NORMALIZATION,
    APPROVED_PASSAGE_PREFIX,
    APPROVED_QUERY_PREFIX,
    APPROVED_WEIGHT_FILENAME,
    APPROVED_WEIGHT_SHA256,
    DEFAULT_BATCH_SIZE,
    DEFAULT_MAXIMUM_ITEMS_PER_RUN,
    DEFAULT_VECTOR_RESULT_LIMIT,
    EMBEDDING_BYTES_LENGTH,
    HARD_MAXIMUM_ITEMS_PER_RUN,
    MAXIMUM_BATCH_SIZE,
    MAXIMUM_QUERY_UTF8_BYTES,
    MAXIMUM_VECTOR_RESULT_LIMIT,
    EmbeddingBoundaryError,
    EmbeddingGenerationRequest,
    EmbeddingGenerationResult,
    EmbeddingModelSpec,
    EmbeddingRecord,
    EmbeddingSource,
    EmbeddingVector,
    Step19ReasonCode,
    VectorRetrievalCandidate,
    VectorRetrievalRequest,
    VectorRetrievalResult,
    load_approved_model_spec,
    normalize_embedding_vector,
    passage_cache_key,
    prepare_passage,
    prepare_query,
    vector_from_float32_bytes,
    vector_sql_literal,
    verify_embedding_record_hash,
    verify_embedding_source_hash,
    verify_generation_request_hash,
    verify_generation_result_hash,
    verify_vector_candidate_hash,
    verify_vector_request_hash,
    verify_vector_result_hash,
)
from .repository import CockroachEmbeddingRepository
from .service import EmbeddingGenerationService, VectorRetrievalService


__all__ = [
    "APPROVED_EMBEDDING_DIMENSION", "APPROVED_INPUT_POLICY",
    "APPROVED_MAXIMUM_TOKENS", "APPROVED_MODEL_ID", "APPROVED_MODEL_LICENSE",
    "APPROVED_MODEL_REVISION", "APPROVED_NORMALIZATION", "APPROVED_PASSAGE_PREFIX",
    "APPROVED_QUERY_PREFIX", "APPROVED_WEIGHT_FILENAME", "APPROVED_WEIGHT_SHA256",
    "CockroachEmbeddingRepository", "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAXIMUM_ITEMS_PER_RUN", "DEFAULT_VECTOR_RESULT_LIMIT",
    "EMBEDDING_BYTES_LENGTH", "EmbeddingBackend", "EmbeddingBackendIdentity",
    "EmbeddingBoundaryError", "EmbeddingGenerationRequest", "EmbeddingGenerationResult",
    "EmbeddingGenerationService", "EmbeddingModelSpec", "EmbeddingRecord",
    "EmbeddingSource", "EmbeddingVector", "HARD_MAXIMUM_ITEMS_PER_RUN",
    "MAXIMUM_BATCH_SIZE", "MAXIMUM_QUERY_UTF8_BYTES", "MAXIMUM_VECTOR_RESULT_LIMIT",
    "PassageEmbeddingBatch", "PassageEmbeddingCache", "Step19ReasonCode",
    "VectorRetrievalCandidate", "VectorRetrievalRequest", "VectorRetrievalResult",
    "VectorRetrievalService", "load_approved_model_spec", "normalize_embedding_vector",
    "passage_cache_key", "prepare_passage", "prepare_query",
    "vector_from_float32_bytes", "vector_sql_literal", "verify_embedding_record_hash",
    "verify_embedding_source_hash", "verify_generation_request_hash",
    "verify_generation_result_hash", "verify_vector_candidate_hash",
    "verify_vector_request_hash", "verify_vector_result_hash",
]
