"""Step 20 hybrid retrieval and frozen Evidence Bundle boundary."""

from .budget import BudgetAssembly, assemble_budgeted_items, utf8_safe_prefix
from .diversity import DiversitySelection, select_diverse_candidates
from .fusion import (
    RankedCandidateInput,
    candidate_rank_key,
    merge_and_rank_candidates,
    modality_for_retrieval_mode,
)
from .models import (
    DEFAULT_CONTEXT_BUDGET_BYTES,
    MAX_BUNDLE_ITEMS,
    MAX_CANONICAL_BUNDLE_BYTES,
    MAX_CONTEXT_BUDGET_BYTES,
    MAX_EXACT_PRIORITY_ITEMS,
    MAX_EXCERPT_BYTES_PER_ITEM,
    MAX_ITEMS_PER_KNOWLEDGE_VERSION,
    MAX_ITEMS_PER_SOURCE,
    MAX_MERGED_CANDIDATES,
    MAX_UPSTREAM_RESULTS_PER_MODALITY,
    MIN_PARTIAL_EXCERPT_BYTES,
    RANKING_POLICY_ID,
    RANKING_POLICY_VERSION,
    RRF_K,
    RRF_SCALE,
    STEP18_RETRIEVAL_POLICY_VERSION,
    STEP20_SCHEMA_VERSION,
    VECTOR_METRIC_POLICY,
    CandidateIdentity,
    DiversityPolicy,
    EvidenceBundleItem,
    EvidenceExcerpt,
    FrozenEvidenceBundle,
    HybridCandidate,
    HybridEvidenceOutcome,
    HybridModality,
    HybridRetrievalRequest,
    ModalityContribution,
    RankingPolicy,
    RetrievalCoverageStatus,
    Step20BoundaryError,
    Step20ReasonCode,
    citation_reference_for,
    evidence_id_for,
    load_diversity_policy,
    load_ranking_policy,
    modality_order,
    modality_weight,
    verify_bundle_item_hash,
    verify_candidate_identity_hash,
    verify_contribution_hash,
    verify_evidence_bundle_hash,
    verify_hybrid_candidate_hash,
    verify_hybrid_request_hash,
    verify_outcome_hash,
)
from .service import (
    PERSISTENCE_DECISION,
    HybridEvidenceService,
    LexicalInput,
    VectorInput,
)


__all__ = [
    "BudgetAssembly", "CandidateIdentity", "DEFAULT_CONTEXT_BUDGET_BYTES",
    "DiversityPolicy", "DiversitySelection", "EvidenceBundleItem",
    "EvidenceExcerpt", "FrozenEvidenceBundle", "HybridCandidate",
    "HybridEvidenceOutcome", "HybridEvidenceService", "HybridModality",
    "HybridRetrievalRequest", "LexicalInput", "MAX_BUNDLE_ITEMS",
    "MAX_CANONICAL_BUNDLE_BYTES", "MAX_CONTEXT_BUDGET_BYTES",
    "MAX_EXACT_PRIORITY_ITEMS", "MAX_EXCERPT_BYTES_PER_ITEM",
    "MAX_ITEMS_PER_KNOWLEDGE_VERSION", "MAX_ITEMS_PER_SOURCE",
    "MAX_MERGED_CANDIDATES", "MAX_UPSTREAM_RESULTS_PER_MODALITY",
    "MIN_PARTIAL_EXCERPT_BYTES", "ModalityContribution",
    "PERSISTENCE_DECISION", "RANKING_POLICY_ID", "RANKING_POLICY_VERSION",
    "RRF_K", "RRF_SCALE", "RankedCandidateInput", "RankingPolicy",
    "RetrievalCoverageStatus", "STEP18_RETRIEVAL_POLICY_VERSION",
    "STEP20_SCHEMA_VERSION", "Step20BoundaryError", "Step20ReasonCode",
    "VECTOR_METRIC_POLICY", "VectorInput", "assemble_budgeted_items",
    "candidate_rank_key", "citation_reference_for", "evidence_id_for",
    "load_diversity_policy", "load_ranking_policy", "merge_and_rank_candidates",
    "modality_for_retrieval_mode", "modality_order", "modality_weight",
    "select_diverse_candidates", "utf8_safe_prefix", "verify_bundle_item_hash",
    "verify_candidate_identity_hash", "verify_contribution_hash",
    "verify_evidence_bundle_hash", "verify_hybrid_candidate_hash",
    "verify_hybrid_request_hash", "verify_outcome_hash",
]
